#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

testString='blah<head>wheee'

FILTER_METHOD='all'
# Piped through itself a few times, because it has to be able to be re-run non-destructively.
result="$(echo "$testString" | ./bin/filter/insertSheet | ./bin/filter/insertSheet | ./bin/filter/insertSheet 2>&1)"
exitCode=$?

if [ "$exitCode" != "0" ]; then
    fail "Got value=\"$result\" and exit code=$exitCode."
elif ! echo "$result" | grep -q '/var/lib/kmailMessageDarkMode/custom.css'; then
    fail "The stylesheet doesn't appear to have been inserted: \"$result\"."
elif ! echo "$result" | grep -q '^blah<head>'; then
    fail "We seem to have lost the beginning of the contents."
elif ! echo "$result" | grep -q 'wheee$'; then
    fail "We seem to have lost the endging of the contents."
else
    pass "Great!"
fi
