#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

testString="<span style=\"font-family:'Calibri';font-size:11pt;color:#000000;background-color:#FFFFFF;color:#FFFFFF\"><font color=\"#a1a2a3\"  color='#a1a2a3'  color =\"#a1a2a3\"  color= \"#a1a2a3\" color = \"#a1a2a3\" bgcolor=\"#C2C3C1\" color=\"#d9213e\"><span style=\"color:white ; color:bright-blue ; color: bright-blue;background:white;color:gray\"><font color=\"#d9213e\">"
expectedResult="<span style=\"font-family:'Calibri';font-size:11pt;;;\"><font          ><span style=\" ;  ; ;;\"><font >"

FILTER_METHOD='all'
# Piped through itself a few times, because it has to be able to be re-run non-destructively.
result="$(echo "$testString" | ./bin/filter/insertSheet | ./bin/filter/insertSheet | ./bin/filter/insertSheet 2>&1)"
exitCode=$?


if [ "$exitCode" != "0" ]; then
    fail "Got value=\"$result\" and exit code=$exitCode."
elif [ "$result" != "$expectedResult" ]; then
    fail "Expected \"$expectedResult\", but got \"$result\"."
else
    pass "Great!"
fi
