#!/bin/bash
# Test for 3D being after = signs. I don't fully understand the reasoning and consequences of this yet. So if someone knows, it would be great for feedback to make sure my solution is adequate, or ways it can be improved.

. "$SHEST_SCRIPT" "--doNothing"

testString="thing=3Dblah"
expectedResult="thing=blah"

FILTER_METHOD='all'
# Piped through itself a few times, because it has to be able to be re-run non-destructively.
result="$(echo "$testString" | ./bin/filter/insertSheet | ./bin/filter/insertSheet | ./bin/filter/insertSheet 2>&1)"
exitCode=$?


if [ "$exitCode" != "0" ]; then
    fail "Got value=\"$result\" and exit code=$exitCode."
elif [ "$result" != "$expectedResult" ]; then
    fail "Expected \"$expectedResult\", but got \"$result\"."
else
    pass "Great!"
fi
