install:
	make install-filter

uninstall:
	make uninstall-filter

install-filter:
	./bin/filter/installBin
	./bin/filter/installSheet ../../sheets/black1-ffffff.css

uninstall-filter:
	rm /usr/bin/insertSheet /var/lib/kmailMessageDarkMode/custom.css

test:
	./bin/filter/testIt
