#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

result="$(echo | ./bin/filter/insertSheet 2>&1)"
exitCode=$?


if [ "$exitCode" == "0" ] ; then
    pass "Great!"
else
    fail "Got value=\"$result\" and exit code=$exitCode."
fi

