#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

testString="<body>thing=
blah</body>"
expectedResult="<body>thingblah</body>"

FILTER_METHOD='all'
# Piped through itself a few times, because it has to be able to be re-run non-destructively.
result="$(echo "$testString" | ./bin/filter/insertSheet | ./bin/filter/insertSheet | ./bin/filter/insertSheet 2>&1)"
exitCode=$?


if [ "$exitCode" != "0" ]; then
    fail "Got value=\"$result\" and exit code=$exitCode."
elif [ "$result" != "$expectedResult" ]; then
    fail "Expected \"$expectedResult\", but got \"$result\"."
else
    pass "Great!"
fi
