#!/bin/bash
# Test to make sure the MIME declaration doesn't get appended to the previous line.

. "$SHEST_SCRIPT" "--doNothing"

testString="         epHA==
MIME-Version: 1.0"
expectedResult="         epHA==
MIME-Version: 1.0"

FILTER_METHOD='all'
# Piped through itself a few times, because it has to be able to be re-run non-destructively.
result="$(echo "$testString" | ./bin/filter/insertSheet | ./bin/filter/insertSheet | ./bin/filter/insertSheet 2>&1)"
exitCode=$?


if [ "$exitCode" != "0" ]; then
    fail "Got value=\"$result\" and exit code=$exitCode."
elif [ "$result" != "$expectedResult" ]; then
    fail "Expected \"$expectedResult\", but got \"$result\"."
else
    pass "Great!"
fi
