install:
	make install-inplace

uninstall:
	make uninstall-inplace

install-inplace:
	./bin/inPlace/installInplace sheets/black1-ffffff.css

uninstall-inplace:
	./bin/inPlace/uninstallInplace

test:
	true
